### ISSUE TITLE
Azurite

### ISSUE THREAD

**Issue by ya-petrov-evgeniy** [testdouble/azure-blob#4]
Hello, how can I use azurite for local testing with activestorage?

**Comment by JoeDupuis** [comment]
It's something I looked at during development but decided to de-prioritize it. I still want to implement it. I’m working on something else that I want to finish first, but I hope to revisit this before the end of the year.

**Comment by igosneves** [comment]
Hello. I was able to test agains azurite local testing with the changes I'm suggesting to the gem in this Pull Request: https://github.com/testdouble/azure-blob/pull/6

I've added to the description the configuration I've done have it running locally against my application that is using the gem.
I haven't updated the test definitions because I've seen they assume an access to an Azure environment, which I don't have at the moment.

**Comment by JoeDupuis** [comment]
Azurite support has been added in 0.5.4.
Thank you @igosneves!

There is instructions in the readme.

**Comment by igosneves** [comment]
Cool, thanks
